<?php
return array(
	'id'             => 'search_fileds',
	'title'          => esc_html__( 'Filtering Fields', 'caleader-listing' ),
	'settings_pages' => 'carleader-listings',
	'tab'            => 'search',
	'fields'         => array(
		array(
			'name'    => esc_html__( 'Hompage Sticky Search', 'caleader-listing' ),
			'id'      => 'home_sticky_seacrh',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Yes', 'caleader-listing' ),
				'0' => esc_html__( 'No', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		),
		array(
			'name'    => esc_html__( 'Hompage Ajax Search', 'caleader-listing' ),
			'id'      => 'home_ajax_seacrh',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Yes', 'caleader-listing' ),
				'0' => esc_html__( 'No', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		),
		array(
			'name'     => esc_html__( 'Select Homepage Filtering Fields', 'caleader-listing' ),
			'id'       => 'home_filter_fileds',
			'type'     => 'select_advanced',
			'multiple' => true,
			'options'  => array(
				'the_year'     => esc_html__( 'Year', 'caleader-listing' ),
				'make'         => esc_html__( 'Make', 'caleader-listing' ),
				'model'        => esc_html__( 'Model', 'caleader-listing' ),
				'condition'    => esc_html__( 'Condition', 'caleader-listing' ),
				'price'        => esc_html__( 'Price', 'caleader-listing' ),
				'body_type'    => esc_html__( 'Body Tyoe', 'caleader-listing' ),
				'odometer'     => esc_html__( 'Odometer', 'caleader-listing' ),
				'transmission' => esc_html__( 'Transmission', 'caleader-listing' ),
				'color'        => esc_html__( 'Color', 'caleader-listing' ),
				'fuel_type'    => esc_html__( 'Fuel Type', 'caleader-listing' ),
			),
		),
		array(
			'name'     => esc_html__( 'Select Archive Filtering Fields', 'caleader-listing' ),
			'id'       => 'archive_filter_fileds',
			'type'     => 'select_advanced',
			'multiple' => true,
			'options'  => array(
				'the_year'     => esc_html__( 'Year', 'caleader-listing' ),
				'make'         => esc_html__( 'Make', 'caleader-listing' ),
				'model'        => esc_html__( 'Model', 'caleader-listing' ),
				'condition'    => esc_html__( 'Condition', 'caleader-listing' ),
				'price'        => esc_html__( 'Price', 'caleader-listing' ),
				'body_type'    => esc_html__( 'Body Tyoe', 'caleader-listing' ),
				'fuel_type'    => esc_html__( 'Fuel Type', 'caleader-listing' ),
				'drivetrain'   => esc_html__( 'Drivetrain', 'caleader-listing' ),
				'transmission' => esc_html__( 'Transmission', 'caleader-listing' ),
				'odometer'     => esc_html__( 'Odometer', 'caleader-listing' ),
				'color'        => esc_html__( 'Color', 'caleader-listing' ),
				'int_color'    => esc_html__( 'Interior Color', 'caleader-listing' ),
			),
		),
	),
);
