<?php
return [
	'id'             => 'page_set',
	'title'          => esc_html__( 'Archive Page Settings', 'caleader-listing' ),
	'settings_pages' => 'carleader-listings',
	'tab'            => 'page_settings',
	'fields'         => [
		[
			'name'        => esc_html__( 'Select a page', 'caleader-listing' ),
			'id'          => 'archive_page',
			'type'        => 'post',
			'post_type'   => 'page',
			'field_type'  => 'select_advanced',
			'placeholder' => esc_html__( 'Select a page', 'caleader-listing' ),
			'query_args'  => array(
				'post_status'    => 'publish',
				'posts_per_page' => - 1,
			),
		],
		[
			'name'    => esc_html__( 'Archive Style', 'caleader-listing' ),
			'id'      => 'archive_layout',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Left Sidebar', 'caleader-listing' ),
				'2' => esc_html__( 'No Sidebar', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		],
		[
			'name'    => esc_html__( 'Archive Layout', 'caleader-listing' ),
			'id'      => 'archive_style',
			'type'    => 'radio',
			'options' => array(
				'grid' => esc_html__( 'Grid', 'caleader-listing' ),
				'list' => esc_html__( 'List', 'caleader-listing' ),
			),
			'std'     => 'grid',
			'inline'  => true,
		],
		[
			'name' => esc_html__( 'Archive Page Name', 'caleader-listing' ),
			'desc' => esc_html__( 'Name of the listing archive page.', 'caleader-listing' ),
			'id'   => 'archive_name',
			'std'  => esc_html__( 'Inventory', 'caleader-listing' ),
			'type' => 'text',
		],
		[
			'name' => esc_html__( 'Archive Page Description', 'caleader-listing' ),
			'desc' => esc_html__( 'Name of the listing archive page.', 'caleader-listing' ),
			'id'   => 'archive_desc',
			'std'  => esc_html__( 'New and Used Inventory Listings:', 'caleader-listing' ),
			'type' => 'text',
		],
		[
			'name'    => esc_html__( 'Layout Selector', 'caleader-listing' ),
			'id'      => 'layout_elector',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Yes', 'caleader-listing' ),
				'0' => esc_html__( 'No', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		],
		[
			'name'    => esc_html__( 'Inventory Ordering', 'caleader-listing' ),
			'id'      => 'inv_orderby',
			'type'    => 'radio',
			'options' => array(
				'date'       => esc_html__( 'New First', 'caleader-listing' ),
				'date-old'   => esc_html__( 'Old First', 'caleader-listing' ),
				'price'      => esc_html__( 'Price (Low to High)', 'caleader-listing' ),
				'price-high' => esc_html__( 'Price (High to Low)', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		],
		[
			'name'    => esc_html__( 'Gallery Icon', 'caleader-listing' ),
			'id'      => 'ga_i',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Yes', 'caleader-listing' ),
				'0' => esc_html__( 'No', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		],
		[
			'name'    => esc_html__( 'Comparison Icon', 'caleader-listing' ),
			'id'      => 'comp_i',
			'type'    => 'radio',
			'options' => array(
				'1' => esc_html__( 'Yes', 'caleader-listing' ),
				'0' => esc_html__( 'No', 'caleader-listing' ),
			),
			'std'     => '1',
			'inline'  => true,
		],
		[
			'name'    => esc_html__( 'Fuel Icon', 'caleader-listing' ),
			'id'      => 'fuel_icon',
			'type'    => 'select',
			'std'     => 'icon-565374',
			'options' => caleader_listing_icon_arr(),
		],
		[
			'name'    => esc_html__( 'Miles Icon', 'caleader-listing' ),
			'id'      => 'miles_icon',
			'type'    => 'select',
			'std'     => 'icon-road',
			'options' => caleader_listing_icon_arr(),
		],
		[
			'name'    => esc_html__( 'Transmission Icon', 'caleader-listing' ),
			'id'      => 'trans_icon',
			'type'    => 'select',
			'std'     => 'icon-2087677',
			'options' => caleader_listing_icon_arr(),
		],
	],
];
